version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: nocodb_nocodb_1
      APP_PORT: 4000
    
  nocodb:
    image: nocodb/nocodb:0.260.2
    container_name: nocodb
    restart: always
    user: "1000:1000"
    ports:
      - "4000:8080"
